lib/fail_dialog.dart
lib/main.dart

✨ Feat: Add 작품 인식 실패 화면

---

lib/main.dart
lib/success_dialog.dart

작품 인식 시 로딩 화면 뜨게 함
작품 인식 > 버튼으로 대체

💄 Design: 카메라 UI 개선 마무리

---

lib/camera_view.dart
lib/main.dart
pubspec.lock
pubspec.yaml

카메라 셔터 UI 생성,  파일 생성 #10
#10
-[] 기능 추가
-[] 의존성, 환경 변수, 빌드 관련 코드 업데이트

✨ Feat: Add 카메라 셔터 UI,  파일 생성

---

lib/camera_view.dart

#7 
- [] 기능 추가
자동으로 켜지는 카메라 플래시 기능 제거

fix: turn off camera flash

---

lib/camera_view.dart
lib/main.dart
lib/success_dialog.dart

ex) #1
1. 사진 찍는 방식 변경: 버튼눌러 찍던 것 -> 화면 더블클릭
2. 실패 팝업 메세지 확인 눌러 끈 후, 10초 후에도 지속적으로 뜨도록 변경
3. 작품 인식 완료 후 진행바 애니메이션 추가

🎨  Fix: 카메라 셔터 방식 변경, 팝업 구조 변경

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
lib/fail_dialog.dart
lib/main.dart

ex) #1
- [O] 기능 추가
1. 작품인식 API 연결
2. 반응형 UI 제작
아직 제미나이가 정상 작동하지 않습니다. 제 터미널에서 영어, 숫자는 잘 출력되는데 한글이 깨져요.
아이폰 15pro를 기준으로 반응형 제작하였습니다.

✨ Feat: 작품 인식 API 연결, 반응형 UI 작업

---

lib/camera_view.dart
lib/main.dart

Fix: 하단바 잘림 문제, 카메라 화면 왜곡 현상

---

ios/Podfile.lock
ios/Runner.xcworkspace/contents.xcworkspacedata
lib/describe_box.dart
lib/describe_page.dart
lib/main.dart
lib/success_dialog.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

ex) #1
- [ O] 기능 추가
촬영한 사진 작품 해설 페이지로 전달
ex)

✨ Feat: 작품해설 페이지 구현

---

lib/bottom_nav_bar.dart
lib/describe_box.dart
lib/main.dart

✨ Feat: 하단 네비게이션바 컴포넌트화

---

lib/describe_box.dart
lib/main.dart

작품해설 페이지 상태 관리 및 UI 개선 #20
#20
작품해설 페이지 상태 관리 및 UI 개선
작품 실패 화면 오류 수정

✨ Feat: 작품해설 페이지 상태 관리 및 UI 개선

---

lib/camera_view.dart
lib/describe_box.dart
lib/main.dart
lib/success_dialog.dart

ex) #1
프로그레스 바 오류 수정, 카메라 줌인줌아웃 추가, 반응형 UI 수정

✨Feat: 진행바 수정, 카메라 줌인 기능 추가

---

lib/camera_view.dart
lib/describe_box.dart
lib/describe_page.dart
lib/main.dart

ex) #1
ex) api 호출이 안되는 문제를 코드 구조를 변경해 해결했습니다.
아직 이미지 호출이 안됩니다..

🔥Feat: 작품 설명 코드 구조 개선

---

ios/Podfile.lock
lib/describe_box.dart

ex) #1
iOS 에서도 tts 재생 가능
그 페이지를 벗어났을 경우 tts가 안멈춥니다..

✨Feat: ios TTS 기능 수정

---

assets/kakaomap.html
lib/bottom_nav_bar.dart
lib/home_screen.dart
lib/search_screen.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

Add: 주변 미술관 api 추가 및 홈화면, 검색화면 ui 구현

---

assets/kakaomap.html
lib/home_screen.dart

Fix: 지도 화면 동작 불가 문제 해결

---

lib/search_screen.dart

Add: 전시회 검색 api 연결

---

lib/describe_box.dart
lib/describe_page.dart
lib/exhibition_detail_page.dart

✨ Feat: 설명 난이도 평가기 구현, 전시회 상세페이지 반응형 구현
설명 난이도 평가기 구현, 전시회 상세페이지 반응형 구현

✨ Feat: 설명 난이도 평가기 구현, 전시회 상세페이지 반응형 구현

---

ios/Podfile.lock
lib/login_google.dart
lib/mypage.dart

구글 로그인 플랫폼 분기 수정, ios cocopad 버전 업그레이드
ex) #1
구글 로그인 플랫폼 분기 수정, ios cocopad 버전 업그레이드

🛠️Fix: 구글 로그인 플랫폼 분기

---

assets/icons/drag_v_handle.svg
assets/icons/dropdown_icon.svg
lib/describe_box.dart
lib/describe_page.dart
lib/success_dialog.dart
pubspec.yaml

🎨Design: 작품 설명 화면 UI 개선
#51 
작품 설명 화면 UI 개선, 작품 인식 전 토큰 불러오는 로직 추가

🎨Design: 작품 설명 화면 UI 개선

---

lib/mypage_bookmark.dart
lib/search_screen.dart

북마크화면 삭제 api 연결, 전시회 제목 검색 결과 최신순 정렬 구현

Add: 북마크화면 삭제 api 연결

---

lib/describe_box.dart
lib/describe_page.dart
lib/main_camera_page.dart
lib/mypage_bookmark.dart
lib/tts_service.dart
lib/utils/auth_storage.dart

+북마크 아이콘, 삭제 api 수정
+tts 토큰 추가
ex) #1

Refac: 작품인식, 해설화면 api 중복 해결 및 토큰 추가

---

lib/mypage_bookmark.dart

Add: 특정 북마크 조회 api 연결

---

lib/app_bar_widget.dart
lib/describe_box.dart
lib/mypage.dart
lib/success_dialog.dart

충돌하는 UI 수정하고 반응형으로 바꿨습니다.
ex) #1
충돌하는 UI 수정하고 반응형으로 바꿨습니다.

🎨 Design: 작품해설 UI 개선

---

lib/describe_box.dart
lib/home_screen.dart
lib/main_camera_page.dart
lib/mypage_bookmark.dart
lib/search_screen.dart

북마크 삭제 시 리스트에 바로 반영되게 바꾸었고, 뒤로 돌아가면 북마크 페이지로 돌아가게 수정함.
ex) #1
북마크 삭제 시 리스트에 바로 반영되게 바꾸었고, 뒤로 돌아가면 북마크 페이지로 돌아가게 수정했습니다.

🛠️Fix: 북마크 삭제 반영, 페이지 간 이동 수정

---

.gitignore
ios/Podfile
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
ios/Runner/AppDelegate.swift
ios/Runner/GoogleService-Info.plist
lib/alarm.dart
lib/main.dart
lib/mypage.dart

알림코드 따로 분리 후 ios 알림 주석처리
ex) #1
알림코드 따로 분리 후 ios 알림 주석처리
gitignore 오타 수정

♻️Refac: 알림코드 분리

---

lib/bottom_nav_bar.dart
lib/community_screen.dart
lib/community_search_screen.dart
pubspec.lock
pubspec.yaml

✨ Feat: 게시물 조회, 검색 기능

---

lib/community_detail_screen.dart
lib/community_screen.dart
lib/community_search_screen.dart
lib/community_write_screen.dart

#71 
게시물 상세보기, 게시물 작성, 댓글 작성 기능 추가

✨ Feat: 게시물 상세보기, 게시물 작성, 댓글 작성 기능 추가

---

lib/ticket_create.dart
lib/ticket_screen.dart
lib/ticket_select_screen.dart

Add: 티켓 추가, 조회, 색상추천 api 연결(색상 반영 보류)

---

assets/images/ticket_detail.svg
lib/alarm_page.dart
lib/ticket_create.dart
lib/ticket_screen.dart
lib/ticket_select_screen.dart
pubspec.lock
pubspec.yaml

티켓 반응형 UI로 수정하고, 알림 UI 및 읽음처리, 삭제 처리 구현했습니다.
ex) #1
티켓 반응형 UI로 수정하고, 알림 UI 및 읽음처리, 삭제 처리 구현했습니다.

🎨Design: 티켓 디자인 수정

---

lib/ticket/ticket_screen.dart

Fix: 티켓 공유 카톡 미리보기 오류 수정(도메인 개설)

---

.gitignore
android/app/build.gradle.kts
android/app/src/main/kotlin/com/example/musai_f/MainActivity.kt
lib/community/community_detail_screen.dart
lib/describe/describe_box.dart
lib/describe/describe_page.dart
lib/mypage/chevron-left.svg
lib/mypage/mypage_bookmark.dart

#90 
예술사조 관련 기능 및 커뮤니티 UI 들여쓰기 수정했습니다.
1. 작품 해설 시, 해당 작품 예술사조 출력
2. 북마크 조회 시, 해당 작품 예술사조 출력
3. 북마크 예술사조별 조회 API 연결
4. 커뮤니티 UI 답글의 답글 들여쓰기 20px (한 번)으로 고정
커뮤니티 댓글 디자인이 따로 안 바뀌어서 그냥 들여쓰기 한 번으로 통일시켰습니다.
작품 해설 화면에 예술사조 추가
북마크 예술사조별 조회
답글 들여쓰기 수정

✨Feat: Update 예술사조 관련 기능 수정

---

ios/Unity/Il2CppOutputProject/Source/il2cppOutput/profile.json
lib/homescreen/home_screen.dart

홈화면의 작품 추천 카드뉴스 UI 수정
ex) #1
홈화면의 작품 추천 카드뉴스 UI 수정

💄Style: 작품추천 카드 UI 수정

---

lib/homescreen/home_screen.dart
lib/homescreen/recommendation_detail_page.dart
lib/homescreen/recommendation_screen.dart
pubspec.lock
pubspec.yaml

Add: 전시회 추천페이지, 추천 상세페이지 구현

---

ios/Runner.xcodeproj/project.pbxproj
ios/Unity/Il2CppOutputProject/Source/il2cppOutput/profile.json
lib/homescreen/home_screen.dart
lib/mypage/mypage.dart

💄Style: 로그아웃 버튼 위치 변경

---

ios/Unity/Il2CppOutputProject/Source/il2cppOutput/profile.json
lib/app_bar_widget.dart
lib/community/community_screen.dart
lib/community/community_search_screen.dart
lib/community/community_write_screen.dart
lib/login/login_UI.dart
lib/login/login_profile.dart
lib/login/preference_page.dart
lib/mypage/mypage.dart
lib/ticket/ticket_create.dart

이미지 업로드 수정 및 일부 UI 수정
ex) #1
이미지 업로드 수정

🛠️Fix: 이미지 업로드 수정

---

ios/.gitignore
ios/Unity/Il2CppOutputProject/Source/il2cppOutput/profile.json
lib/app_bar_widget.dart
lib/community/community_detail_screen.dart
lib/community/community_write_screen.dart
lib/homescreen/home_screen.dart
lib/homescreen/recommendation_detail_page.dart
lib/homescreen/recommendation_screen.dart
lib/ticket/ticket_create.dart

지도까지 다 스크롤되게 수정하였고, 지도 작동 시 스크롤 안되게 고정하였습니다.
작품 추천 누를 시 상세페이지로 이동하며, +를 눌러야 추천리스트페이지로 이동하게 수정했습니다.
ex) #1
지도까지 다 스크롤되게 수정하였고, 지도 작동 시 스크롤 안되게 고정하였습니다.
작품 추천 누를 시 상세페이지로 이동하며, +를 눌러야 추천리스트페이지로 이동하게 수정했습니다.

💄Style: 홈화면 UI 수정

---

android/app/build.gradle.kts
android/app/proguard-rules.pro

♻️Refac: 난독화 작업

---

README.md

📝Docs: README 수정
